### ISSUE TITLE
Add "declares" level to measure how many files has declare strict types

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/type-coverage#34]
What if we have 100 % type declaratoins coverage, but zero strict declares? 

We want to catch those files too :wink: 

```yaml
parameters:
    type_coverage:
        declare: 70
```

```php
<?php

class SomeClass
{
	public funciton getNameFor(int $userId): string
	{
		// ...
	}
}
```

↓

PHPStan output:

```bash
Out of 1 possible declare(strict_types=1), only 0 - 0.0 % actually have it. 
Add more declares to get over 70 %
```
